In [ ]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df= pd.read_csv(f"https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df.shape

(569, 31)

In [ ]:
# Train test split
X_train, X_test,y_train,y_test= train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [ ]:
X_train.shape

(455, 30)

In [ ]:
# Scaling
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [ ]:
y_train

216    B
487    M
202    M
217    B
565    M
      ..
233    M
183    B
511    B
326    B
84     B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
# Label Encoder
encoder= LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test= encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0])

In [ ]:
# Numpy arrays to pytorch
X_train_tensor= torch.from_numpy(X_train.astype(np.float32))
X_test_tensor= torch.from_numpy(X_test.astype(np.float32))
y_train_tensor= torch.from_numpy(y_train.astype(np.float32))
y_test_tensor= torch.from_numpy(y_test.astype(np.float32))

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
# Defining the model
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear= nn.Linear(num_features,1)
    self.sigmoid= nn.Sigmoid()

  def forward(self, features):
    out= self.linear(features)
    out= self.sigmoid(out)
    return out

  def loss_function(self,y_pred, y):
    # Clamp prediction to avoid log(0)
    epsilon= 1e-7
    y_pred= torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss= - (y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred))
    return loss.mean()

In [ ]:
# Important Parameter

learning_rate=0.1
epochs=25

In [ ]:
# Training Pipeline

# create model
model=MySimpleNN(X_train_tensor.shape[1])
# define loop
for epoch in range(epochs):
  # forward pass
  y_pred= model.forward(X_train_tensor)
  # loss calculate
  loss= model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameter update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # Print loss in each epochs

  print(f"Epoch: {epoch} Loss: {loss}")

Epoch: 0 Loss: 0.7572986483573914
Epoch: 1 Loss: 0.7329579591751099
Epoch: 2 Loss: 0.717164158821106
Epoch: 3 Loss: 0.7066449522972107
Epoch: 4 Loss: 0.6992943286895752
Epoch: 5 Loss: 0.6938703060150146
Epoch: 6 Loss: 0.6896659731864929
Epoch: 7 Loss: 0.6862770915031433
Epoch: 8 Loss: 0.6834641695022583
Epoch: 9 Loss: 0.6810775995254517
Epoch: 10 Loss: 0.6790183782577515
Epoch: 11 Loss: 0.6772171854972839
Epoch: 12 Loss: 0.6756234169006348
Epoch: 13 Loss: 0.6741990447044373
Epoch: 14 Loss: 0.6729146838188171
Epoch: 15 Loss: 0.6717474460601807
Epoch: 16 Loss: 0.6706793904304504
Epoch: 17 Loss: 0.6696962118148804
Epoch: 18 Loss: 0.6687864661216736
Epoch: 19 Loss: 0.6679407954216003
Epoch: 20 Loss: 0.6671518683433533
Epoch: 21 Loss: 0.6664133071899414
Epoch: 22 Loss: 0.6657201647758484
Epoch: 23 Loss: 0.6650679111480713
Epoch: 24 Loss: 0.6644532084465027

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.1230, -0.1084, -0.1827,  0.1513, -0.0539,  0.0698,  0.0700,  0.0700,
          0.0429, -0.0332,  0.1171,  0.0914, -0.1031, -0.0002, -0.0835, -0.0540,
          0.1776, -0.0870,  0.0544, -0.1232,  0.1743,  0.0316,  0.0564, -0.1581,
         -0.0450,  0.0326, -0.0007, -0.0583, -0.1015,  0.0660]],
       requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.3198], requires_grad=True)

In [ ]:
# Model Evaluation
with torch.no_grad():
  y_pred= model.forward(X_test_tensor)
  y_pred= (y_pred > 0.5).float()
  accuracy= (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5581717491149902

Using built in Loss function

In [ ]:
# Defining the model
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear= nn.Linear(num_features,1)
    self.sigmoid= nn.Sigmoid()

  def forward(self, features):
    out= self.linear(features)
    out= self.sigmoid(out)
    return out

In [ ]:
# important Parameters
learning_rate=0.1
epochs= 25

In [ ]:
loss_function= nn.BCELoss()

In [ ]:
# Training Pipeline

# create model
model=MySimpleNN(X_train_tensor.shape[1])
# define loop
for epoch in range(epochs):
  # forward pass
  y_pred=model(X_train_tensor)
  # loss calculate
  loss= loss_function(y_pred, y_train_tensor.reshape(-1,1))
  # or   loss= loss_function(y_pred, y_train_tensor.view(-1,1)) for reshape the y_train_tensor by usng reshape or view , view for continious data


  # backward pass
  loss.backward()

  # parameter update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # Print loss in each epochs

  print(f"Epoch: {epoch} Loss: {loss}")

Epoch: 0 Loss: 0.7705268859863281
Epoch: 1 Loss: 0.5518556237220764
Epoch: 2 Loss: 0.4424441158771515
Epoch: 3 Loss: 0.3800241947174072
Epoch: 4 Loss: 0.33903974294662476
Epoch: 5 Loss: 0.30957576632499695
Epoch: 6 Loss: 0.28709766268730164
Epoch: 7 Loss: 0.26922407746315
Epoch: 8 Loss: 0.25457262992858887
Epoch: 9 Loss: 0.24227942526340485
Epoch: 10 Loss: 0.2317734956741333
Epoch: 11 Loss: 0.22266051173210144
Epoch: 12 Loss: 0.21465815603733063
Epoch: 13 Loss: 0.20755843818187714
Epoch: 14 Loss: 0.2012040913105011
Epoch: 15 Loss: 0.19547390937805176
Epoch: 16 Loss: 0.19027265906333923
Epoch: 17 Loss: 0.18552426993846893
Epoch: 18 Loss: 0.18116724491119385
Epoch: 19 Loss: 0.1771511733531952
Epoch: 20 Loss: 0.17343425750732422
Epoch: 21 Loss: 0.16998161375522614
Epoch: 22 Loss: 0.16676375269889832
Epoch: 23 Loss: 0.16375558078289032
Epoch: 24 Loss: 0.16093562543392181

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.1599,  0.2043,  0.2783,  0.2275,  0.1224,  0.0542,  0.0692,  0.2377,
          0.0061, -0.0887,  0.1349,  0.0417,  0.1861,  0.0499,  0.0568, -0.0495,
         -0.1024,  0.1102, -0.1165,  0.0714,  0.3346,  0.1477,  0.2590,  0.4037,
          0.2483,  0.2692,  0.3146,  0.3124,  0.1483, -0.0305]],
       requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.1580], requires_grad=True)

In [ ]:
# Model Evaluation
with torch.no_grad():
  y_pred= model.forward(X_test_tensor)
  y_pred= (y_pred > 0.5).float()
  accuracy= (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5947983860969543

Uisng Built in optimization
by  using optim()

In [ ]:
#define optimizer
#optimizer= torch.optim.SGD(model.parameters(), lr=learning_rate)

In [ ]:
# Defining the model
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear= nn.Linear(num_features,1)
    self.sigmoid= nn.Sigmoid()

  def forward(self, features):
    out= self.linear(features)
    out= self.sigmoid(out)
    return out

In [ ]:
# important Parameters
learning_rate=0.1
epochs= 25

In [ ]:
loss_function= nn.BCELoss()

In [ ]:
# Training Pipline
# Create Model
model= MySimpleNN(X_train_tensor.shape[1])

 # Define Oprimizer
optimizers= torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define loop
for epoch in range(epochs):
  # forward pass
  y_pred= model(X_train_tensor)

  # loss calculate
  loss= loss_function(y_pred, y_train_tensor.view(-1,1))

   # clear  gradients
  optimizers.zero_grad()

  # backward pass
  loss.backward()

  # parameter update
  optimizers.step()



  #print  loss in each epoches
  print(f"Epoch: {epoch} Loss: {loss}")

Epoch: 0 Loss: 0.7846287488937378
Epoch: 1 Loss: 0.5643686056137085
Epoch: 2 Loss: 0.4555056393146515
Epoch: 3 Loss: 0.3929820954799652
Epoch: 4 Loss: 0.35177698731422424
Epoch: 5 Loss: 0.32215625047683716
Epoch: 6 Loss: 0.29959991574287415
Epoch: 7 Loss: 0.2817094027996063
Epoch: 8 Loss: 0.26708415150642395
Epoch: 9 Loss: 0.25484633445739746
Epoch: 10 Loss: 0.24441483616828918
Epoch: 11 Loss: 0.23538833856582642
Epoch: 12 Loss: 0.22747953236103058
Epoch: 13 Loss: 0.2204769402742386
Epoch: 14 Loss: 0.21422097086906433
Epoch: 15 Loss: 0.2085886299610138
Epoch: 16 Loss: 0.2034834325313568
Epoch: 17 Loss: 0.1988285779953003
Epoch: 18 Loss: 0.1945619285106659
Epoch: 19 Loss: 0.19063276052474976
Epoch: 20 Loss: 0.1869991272687912
Epoch: 21 Loss: 0.18362590670585632
Epoch: 22 Loss: 0.18048368394374847
Epoch: 23 Loss: 0.1775473952293396
Epoch: 24 Loss: 0.17479561269283295

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.1311,  0.1099,  0.2378,  0.1268,  0.1339,  0.1936,  0.1632,  0.3536,
         -0.0358, -0.1722,  0.2413,  0.0676,  0.2784,  0.1194,  0.0236,  0.0747,
         -0.0697,  0.0043, -0.1365, -0.1027,  0.3617,  0.1735,  0.3198,  0.1474,
          0.2385,  0.1244,  0.1229,  0.3574,  0.1471,  0.1468]],
       requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.2227], requires_grad=True)

In [ ]:
# Model Evaluation
with torch.no_grad():
  y_pred= model.forward(X_test_tensor)
  y_pred= (y_pred > 0.5).float()
  accuracy= (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5393967628479004