In [ ]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df= pd.read_csv(f"https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df.shape

(569, 31)

In [ ]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

Trin test split

In [ ]:
X_train,X_test, y_train, y_test= train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)

Scaling

In [ ]:
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [ ]:
X_train

array([[ 0.38715717,  0.21338821,  0.31912172, ...,  0.54696545,
         0.86381022,  0.14239336],
       [-0.78935597, -0.21787254, -0.81177222, ..., -0.77296419,
        -0.27858652, -1.10051618],
       [-0.56525823, -0.80911712, -0.5869706 , ..., -1.03036982,
        -0.70145361, -1.20544465],
       ...,
       [ 1.21351758, -0.41495407,  1.23047966, ...,  1.79305287,
         1.45713536,  0.46355562],
       [ 1.72614116,  0.48002792,  1.58692187, ...,  0.40404503,
        -1.10137442, -0.72949841],
       [-0.12546641,  0.30381385, -0.14384811, ..., -0.72815268,
        -1.08334521,  0.06181294]])

In [ ]:
y_train

182    M
251    B
189    B
305    B
487    M
      ..
427    B
180    M
45     M
237    M
544    B
Name: diagnosis, Length: 455, dtype: object

Encoder

In [ ]:
encoder= LabelEncoder()

y_train= encoder.fit_transform(y_train)
y_test= encoder.transform(y_test)

In [ ]:
y_train

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0])

Numpy arrays to PyTorch  tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor= torch.from_numpy(X_test.astype(np.float32))
y_train_tensor= torch.from_numpy(y_train.astype(np.float32))
y_test_tensor= torch.from_numpy(y_test.astype(np.float32))

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
from torch.utils.data import Dataset, DataLoader
class CustomDataset(Dataset):
  def __init__(self,features, lables):
    self.features= features
    self.lables= lables

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.lables[idx]

In [ ]:
train_dataset= CustomDataset(X_train_tensor, y_train_tensor)
test_dataset= CustomDataset(X_test_tensor, y_test_tensor)

In [ ]:
train_dataset[1]

(tensor([-0.7894, -0.2179, -0.8118, -0.7377, -0.2288, -0.8738, -0.8178, -0.7561,
          0.0406, -0.4958, -0.0749, -0.6917, -0.1240, -0.3134, -0.1999, -0.8700,
         -0.7326, -0.4505,  0.2930, -1.0080, -0.7262, -0.5424, -0.7607, -0.6896,
         -0.6084, -0.9912, -0.9610, -0.7730, -0.2786, -1.1005]),
 tensor(0.))

In [ ]:
train_loader= DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader= DataLoader(test_dataset, batch_size=32, shuffle=True)

Definind the model

In [ ]:
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear= nn.Linear(num_features,1)
    self.sigmoid= nn.Sigmoid()

  def forward(self, features):
    out= self.linear(features)
    out= self.sigmoid(out)
    return out

Important Parameters

In [ ]:
learning_rate= 0.1
epochs=25

In [ ]:
# Create model
model= MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer= torch.optim.SGD(model.parameters(), lr=learning_rate)

#define loss function
loss_fn= nn.BCELoss()

Training Pipeline

In [ ]:
# Definr loop
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:
    # forward pass
    y_pred= model(batch_features)

    #calculate loss
    loss= loss_fn(y_pred, batch_labels.view(-1,1))

    # clear gradient
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # update weights
    optimizer.step()

  print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item()}")

Epoch 1/25, Loss: 0.1454944610595703
Epoch 2/25, Loss: 0.18037983775138855
Epoch 3/25, Loss: 0.12592168152332306
Epoch 4/25, Loss: 0.25913605093955994
Epoch 5/25, Loss: 0.10271566361188889
Epoch 6/25, Loss: 0.11940409243106842
Epoch 7/25, Loss: 0.08909887075424194
Epoch 8/25, Loss: 0.034481216222047806
Epoch 9/25, Loss: 0.038089048117399216
Epoch 10/25, Loss: 0.06368844956159592
Epoch 11/25, Loss: 0.036016497761011124
Epoch 12/25, Loss: 0.020266082137823105
Epoch 13/25, Loss: 0.026740485802292824
Epoch 14/25, Loss: 0.015056140720844269
Epoch 15/25, Loss: 0.028891021385788918
Epoch 16/25, Loss: 0.09859902411699295
Epoch 17/25, Loss: 0.08830640465021133
Epoch 18/25, Loss: 0.021232962608337402
Epoch 19/25, Loss: 0.03435386344790459
Epoch 20/25, Loss: 0.06308882683515549
Epoch 21/25, Loss: 0.05679384246468544
Epoch 22/25, Loss: 0.05945812910795212
Epoch 23/25, Loss: 0.006503434386104345
Epoch 24/25, Loss: 0.022956952452659607
Epoch 25/25, Loss: 0.08326084911823273

In [ ]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9219